//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AddPlayerToCompanyBodyDto {
    playerId?: number | undefined;
    companyId?: number | undefined;
}

export interface AssignCategoryToPlayerBodyDto {
    categoryId?: number | undefined;
    playerId?: number | undefined;
}

export interface AssignCodesCollectionToPlayerBodyDto {
    unassignedCollectionId?: number | undefined;
    playerId?: number | undefined;
    discountType?: DiscountType;
    startDate?: Date;
    endDate?: Date;
}

export interface BaseResponse {
    message?: string | undefined;
}

export enum BasicRole {
    _1 = 1,
    _2 = 2,
}

export interface Category {
    id?: number | undefined;
    name?: string | undefined;
    description?: string | undefined;
    players?: Player[] | undefined;
    vouchers?: Voucher[] | undefined;
    playerCategories?: PlayerCategories[] | undefined;
}

export interface CategoryBodyDto {
    id?: number;
    name?: string | undefined;
    description?: string | undefined;
}

export interface CategoryFindByNameResponseDto {
    message?: string | undefined;
    categories?: CategoryBodyDto[] | undefined;
}

export interface CategoryMainResponseDto {
    message?: string | undefined;
    category?: CategoryBodyDto;
}

export interface ChangeRoleBodyDto {
    userName?: string | undefined;
    userId?: string | undefined;
    role?: BasicRole;
}

export interface CompaniesWithPlayersBodyDto {
    companyName?: string | undefined;
    playerName?: string | undefined;
}

export interface Company {
    id?: number | undefined;
    name?: string | undefined;
    address?: string | undefined;
    numberOfEmployees?: number | undefined;
    contactDate?: Date;
    users?: User[] | undefined;
    players?: Player[] | undefined;
    companyPlayers?: CompanyPlayer[] | undefined;
}

export interface CompanyBodyDto {
    id?: number;
    name?: string | undefined;
    address?: string | undefined;
    numberOfEmployees?: number | undefined;
}

export interface CompanyFindByNameResponseDto {
    message?: string | undefined;
    companies?: CompanyBodyDto[] | undefined;
}

export interface CompanyMainResponseDto {
    message?: string | undefined;
    company?: CompanyBodyDto;
}

export interface CompanyPlayer {
    id?: number | undefined;
    companyId?: number;
    company?: Company;
    playerId?: number;
    player?: Player;
}

export interface CreateNewCategoryBodyDto {
    name?: string | undefined;
    description?: string | undefined;
}

export interface CreateNewCompanyBodyDto {
    name?: string | undefined;
    address?: string | undefined;
    numberOfEmployees?: number | undefined;
}

export interface CreateNewEntityResponseDto {
    message?: string | undefined;
    id?: number | undefined;
}

export interface CreateNewPlayerBodyDto {
    shortName?: string | undefined;
    fullName?: string | undefined;
    categoryId?: number | undefined;
    playStoreLink?: string | undefined;
    appStoreLink?: string | undefined;
    linkDescription?: string | undefined;
    color?: string | undefined;
}

export interface CreateNewVoucherBodyDto {
    name?: string | undefined;
    categoryId?: number;
    discountId?: number;
}

export interface CsvToDiscountCodesResponseDto {
    message?: string | undefined;
    unassignedCollectionId?: number | undefined;
}

export interface DeleteCategoryFromPlayerBodyDto {
    categoryId?: number | undefined;
    playerId?: number | undefined;
}

export interface DeleteResponseDto {
    message?: string | undefined;
    isDeleted?: boolean;
}

export interface Discount {
    id?: number | undefined;
    discountCode?: DiscountCode;
    discountCodeId?: number | undefined;
    playerId?: number | undefined;
    linkTermsAndConditions?: string | undefined;
    unityOfMeasurement?: string | undefined;
    discountValue?: number | undefined;
    numberOfUsagePerCompany?: number | undefined;
    numberOfUsagePerUser?: number | undefined;
    initialPrice?: number | undefined;
    finalPrice?: number | undefined;
    discountType?: DiscountType;
    player?: Player;
    validityPeriod?: ValidityPeriod;
    vouchers?: Voucher[] | undefined;
}

export interface DiscountCode {
    id?: number | undefined;
    code?: string | undefined;
    discount?: Discount;
    unassignedCollectionId?: number | undefined;
    unassignedDiscountCodeCollections?: UnassignedDiscountCodeCollection;
}

export enum DiscountType {
    _0 = 0,
    _1 = 1,
    _2 = 2,
}

export interface GetAllCategoriesForPlayerResponseDto {
    message?: string | undefined;
    categories?: CategoryBodyDto[] | undefined;
}

export interface GetAllCategoriesResponseDto {
    message?: string | undefined;
    categories?: CategoryBodyDto[] | undefined;
}

export interface GetAllCompaniesResponseDto {
    message?: string | undefined;
    companies?: CompanyBodyDto[] | undefined;
}

export interface GetAllCompaniesWithPlayersResponseDto {
    message?: string | undefined;
    companies?: CompaniesWithPlayersBodyDto[] | undefined;
}

export interface GetAllPlayersForCurrentCompanyResponseDto {
    message?: string | undefined;
    players?: Player[] | undefined;
}

export interface GetAllPlayersResponseDto {
    message?: string | undefined;
    players?: PlayerBodyDto[] | undefined;
}

export interface GetAllUsersForCompanyResponseDto {
    message?: string | undefined;
    users?: User[] | undefined;
}

export interface GetAllUsersResponseDto {
    message?: string | undefined;
    users?: UserDto[] | undefined;
}

export interface GetAllVouchersResponseDto {
    message?: string | undefined;
    vouchers?: VoucherBodyDto[] | undefined;
}

export interface IdentityError {
    code?: string | undefined;
    description?: string | undefined;
}

export interface IdentityResult {
    readonly succeeded?: boolean;
    readonly errors?: IdentityError[] | undefined;
}

export interface IdentityUserDto {
    userName?: string | undefined;
    password?: string | undefined;
    companyId?: number;
}

export interface Location {
    id?: number | undefined;
    city?: string | undefined;
    region?: string | undefined;
    postalCode?: string | undefined;
    players?: Player[] | undefined;
    playerLocations?: PlayerLocation[] | undefined;
}

export interface LoginBodyDto {
    userName?: string | undefined;
    password?: string | undefined;
}

export interface Player {
    id?: number | undefined;
    shortName?: string | undefined;
    fullName?: string | undefined;
    playStoreLink?: string | undefined;
    appStoreLink?: string | undefined;
    linkDescription?: string | undefined;
    color?: string | undefined;
    categories?: Category[] | undefined;
    discounts?: Discount[] | undefined;
    locations?: Location[] | undefined;
    playerLocations?: PlayerLocation[] | undefined;
    playerCategories?: PlayerCategories[] | undefined;
    playerContacts?: PlayerContact[] | undefined;
    companies?: Company[] | undefined;
    companyPlayers?: CompanyPlayer[] | undefined;
}

export interface PlayerBodyDto {
    id?: number;
    shortName?: string | undefined;
    fullName?: string | undefined;
    playStoreLink?: string | undefined;
    appStoreLink?: string | undefined;
    linkDescription?: string | undefined;
    color?: string | undefined;
}

export interface PlayerCategories {
    id?: number | undefined;
    playerId?: number | undefined;
    player?: Player;
    categoryId?: number | undefined;
    category?: Category;
}

export interface PlayerContact {
    id?: number | undefined;
    name?: string | undefined;
    surname?: string | undefined;
    email?: string | undefined;
    phoneNumber?: number;
    player?: Player;
    playerId?: number;
}

export interface PlayerFindByNameResponseDto {
    message?: string | undefined;
    players?: PlayerBodyDto[] | undefined;
}

export interface PlayerLocation {
    id?: number | undefined;
}

export interface PlayerMainResponseDto {
    message?: string | undefined;
    player?: PlayerBodyDto;
}

export interface UnassignedDiscountCodeCollection {
    id?: number | undefined;
    discountCodes?: DiscountCode[] | undefined;
}

export interface User {
    id?: number | undefined;
    identityUserId?: string | undefined;
    companyId?: number;
    company?: Company;
}

export interface UserDto {
    id?: string | undefined;
    userName?: string | undefined;
}

export interface ValidityPeriod {
    id?: number | undefined;
    startDate?: Date;
    endDate?: Date;
}

export interface Voucher {
    id?: number | undefined;
    name?: string | undefined;
    category?: Category;
    categoryId?: number;
    discount?: Discount;
    discountId?: number;
}

export interface VoucherBodyDto {
    id?: number;
    name?: string | undefined;
    categoryId?: number;
    discountId?: number;
}

export interface VoucherMainResponseDto {
    message?: string | undefined;
    voucher?: VoucherBodyDto;
}